# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0016_auto_20200401_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='FocusArea',
            field=models.TextField(default=b'C++'),
        ),
    ]
