# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0018_coursetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='course_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_type', to='course_overviews.CourseType'),
        ),
    ]
