# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0019_courseoverview_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCustomDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_keys', models.TextField(null=True)),
                ('display_name', models.TextField(null=True)),
                ('Duration', models.IntegerField(default=60)),
                ('FocusArea', models.TextField(default=b'C++')),
                ('course_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_details_type', to='course_overviews.CourseType')),
            ],
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='course_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='course_overviews.CourseCustomDetails'),
        ),
    ]
