# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0020_auto_20200423_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecustomdetails',
            old_name='course_keys',
            new_name='course_key',
        ),
        migrations.RemoveField(
            model_name='courseoverview',
            name='course_details',
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='course_custom_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_custom_details', to='course_overviews.CourseCustomDetails'),
        ),
    ]
