# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0021_auto_20200423_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecustomdetails',
            options={'verbose_name': 'Course Custom Details', 'verbose_name_plural': 'Course Custom Details'},
        ),
        migrations.AlterField(
            model_name='coursecustomdetails',
            name='FocusArea',
            field=models.TextField(default=b'N/A'),
        ),
    ]
