# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0022_auto_20200519_1707'),
        ('course_overviews', '0022_auto_20200427_0740'),
    ]

    operations = [
    ]
