# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0024_coursecustomdetails_course_type_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecustomdetails',
            name='course_instructions',
            field=models.TextField(null=True),
        ),
    ]
