# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_coursecustomdetails_course_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecustomdetails',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='courseoverview',
            name='course_type',
        ),
        migrations.AlterField(
            model_name='coursecustomdetails',
            name='course_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecustomdetails',
            name='course_type_choice',
            field=models.CharField(choices=[(b'Application', b'APPLICATION'), (b'Assessment', b'ASSESSMENT'), (b'Course', b'COURSE'), (b'Project', b'PROJECT')], default=b'Course', max_length=50),
        ),
        migrations.DeleteModel(
            name='CourseType',
        ),
    ]
