# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_auto_20200825_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecustomdetails',
            name='organization_logo_url',
            field=models.TextField(null=True),
        ),
    ]
