# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0020_auto_20200423_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_points', models.TextField(null=True)),
                ('program_overview', models.TextField(null=True)),
                ('instructors', models.TextField(null=True)),
                ('duration', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=0)),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programlist_identifier', to='student.CourseIdentifier')),
            ],
            options={
                'db_table': 'programs_programlist',
                'verbose_name': 'program list',
            },
        ),
        migrations.CreateModel(
            name='UserPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprogram_user', to='user_programs.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprogram_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programs_userprograms',
                'verbose_name': 'User Programs',
            },
        ),
    ]
