# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_name',
            field=models.CharField(default='Program', max_length=100),
            preserve_default=False,
        ),
    ]
