# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0002_program_program_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprograms',
            options={'verbose_name': 'User Program'},
        ),
        migrations.AddField(
            model_name='program',
            name='focus_area',
            field=models.CharField(default='Dot Net', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
