# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0003_auto_20200520_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='weekly_duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
