# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0004_auto_20200527_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprograms',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
    ]
