# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-01 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0004_auto_20200527_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='support',
            field=models.TextField(null=True),
        ),
    ]
