# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0005_userprograms_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprograms',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
