# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-01 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0005_program_support'),
        ('user_programs', '0006_auto_20200530_0502'),
    ]

    operations = [
    ]
