# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0009_auto_20200603_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='last_modified_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_schedule',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprograms',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='userprograms',
            name='last_modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
