# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-22 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0010_auto_20200610_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_sessions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
