# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0014_auto_20200825_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitygroup',
            name='entity_group_type',
            field=models.CharField(choices=[(b'Program', b'PROGRAM'), (b'Project', b'PROJECT')], default='Program', max_length=50),
        ),
        migrations.AlterField(
            model_name='entitygroup',
            name='last_modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
