# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-07 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_programs', '0015_auto_20200825_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitygroup',
            name='organization_logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
