# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-19 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edx_proctoring', '0009_proctoredexamreviewpolicy_remove_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDEExamAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_url', models.CharField(max_length=200)),
                ('container_created_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ide_ideexam_attempt',
                'verbose_name': 'IDE Exam Attempt',
            },
        ),
        migrations.CreateModel(
            name='IDEExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('container_command', models.CharField(max_length=200)),
                ('max_score', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('proctored_exam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideexam_exam', to='edx_proctoring.ProctoredExam')),
            ],
            options={
                'db_table': 'ide_ideexam',
                'verbose_name': 'IDE Exam',
            },
        ),
        migrations.AddField(
            model_name='ideexamattempt',
            name='ide_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ide_attempt_exam', to='IDE_Exam.IDEExams'),
        ),
        migrations.AddField(
            model_name='ideexamattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ide_attempt_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
