# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE_Exam', '0002_auto_20200619_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideexams',
            name='is_embedded',
            field=models.BooleanField(default=True),
        ),
    ]
