# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE_Exam', '0004_auto_20200625_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideexamattempt',
            name='container_port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ideexams',
            name='container_command',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ideexams',
            name='server_ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
