# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE_Exam', '0005_auto_20200702_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideexamattempt',
            name='git_detais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
