# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE_Exam', '0006_ideexamattempt_git_detais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideexamattempt',
            name='container_created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ideexamattempt',
            name='container_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
