# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE_Exam', '0007_auto_20200807_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideexams',
            name='git_fork_repository',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
