# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE_Exam', '0008_ideexams_git_fork_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideexamattempt',
            name='container_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ideexamattempt',
            name='container_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
