# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-26 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE_Exam', '0009_auto_20200814_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideexams',
            name='enable_git_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
