# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edx_proctoring', '0009_proctoredexamreviewpolicy_remove_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('is_coding', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('proctored_exam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codingexam_exam', to='edx_proctoring.ProctoredExam')),
            ],
            options={
                'db_table': 'coding_exams',
                'verbose_name': 'Coding Exam',
            },
        ),
        migrations.CreateModel(
            name='CodingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=200)),
                ('snippet_id', models.CharField(max_length=50)),
                ('snippet_url', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100, null=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('coding_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_attempt_exam', to='code_editor.CodingExams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_attempt_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coding_studentattempt',
                'verbose_name': 'Coding Attempt',
            },
        ),
    ]
