# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingexams',
            name='code_copy_paste_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codingexams',
            name='code_run_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='codingexams',
            name='coding_Languages',
            field=models.CharField(default='', max_length=200),
        ),
    ]
