# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-17 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0002_auto_20200617_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingexams',
            old_name='code_run_option',
            new_name='enable_code_run',
        ),
        migrations.RenameField(
            model_name='codingexams',
            old_name='code_copy_paste_option',
            new_name='enable_copy_paste',
        ),
    ]
