# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0003_auto_20200617_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingexams',
            name='evaluvation_parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingresult',
            name='evaluvation_parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
