# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0005_auto_20200626_0712'),
        ('code_editor', '0005_codingresult_remarks'),
    ]

    operations = [
    ]
