# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0009_codingresult_is_submit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodingExams',
            new_name='CodingQuestion',
        ),
        migrations.AlterModelOptions(
            name='codingquestion',
            options={'verbose_name': 'Coding Questions'},
        ),
        migrations.AlterModelTable(
            name='codingquestion',
            table='coding_questions',
        ),
    ]
