# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0010_auto_20200708_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingquestion',
            old_name='is_coding',
            new_name='auto_evaluation',
        ),
        migrations.RenameField(
            model_name='codingquestion',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='codingresult',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='codingresult',
            old_name='evaluvation_parameters',
            new_name='evaluation_details',
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='default_snippet_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 45, 33, 428651)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='question_id',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='unit_id',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingresult',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 46, 41, 114719)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='proctored_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codingexam_exam', to='edx_proctoring.ProctoredExam'),
        ),
    ]
