# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0011_auto_20200708_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
