# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0012_codingquestion_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='coding_Languages_type',
            field=models.CharField(choices=[(b'BACKEND', b'BACKEND'), (b'DATABASE', b'DATABASE'), (b'DEVOPS', b'DEVOPS'), (b'FRONTEND', b'FRONTEND')], max_length=50),
        ),
    ]
