# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0014_codingquestion_result_snippet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='allow_main_method',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='codingresult',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
