# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-06 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0015_auto_20200814_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='snippet_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
