# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-10 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0016_codingresult_snippet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingresult',
            name='snippet_text',
            field=models.TextField(null=True),
        ),
    ]
