# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-12 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0017_auto_20211010_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='snippet_language',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
