# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-18 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0018_codingresult_snippet_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_name', models.CharField(max_length=200)),
                ('snippet_id', models.CharField(max_length=200)),
                ('snippet_text', models.TextField(null=True)),
                ('coding_Languages_type', models.CharField(choices=[(b'BACKEND', b'BACKEND'), (b'DATABASE', b'DATABASE'), (b'DEVOPS', b'DEVOPS'), (b'FRONTEND', b'FRONTEND')], max_length=50)),
            ],
            options={
                'db_table': 'default_snippets',
                'verbose_name': 'Default Snippet',
            },
        ),
    ]
