# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-18 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0019_defaultsnippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codingquestion',
            options={'verbose_name': 'Coding Question'},
        ),
    ]
