# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-18 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0020_auto_20211018_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultsnippet',
            name='id',
        ),
        migrations.AlterField(
            model_name='defaultsnippet',
            name='snippet_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
