# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0021_auto_20211018_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsnippet',
            name='coding_language',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
