# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0024_auto_20211028_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='test_cases_stdin',
        ),
        migrations.RemoveField(
            model_name='codingquestion',
            name='test_result_stdout',
        ),
        migrations.AddField(
            model_name='codingresult',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='codingresult',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
