# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edx_proctoring', '0009_proctoredexamreviewpolicy_remove_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('status', models.TextField(blank=True)),
                ('proctored_attempt', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctoringdata_exam', to='edx_proctoring.ProctoredExamStudentAttempt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoringdata_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoringsystem_proctoringdata',
                'verbose_name': 'proctoring system data',
            },
        ),
    ]
