# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_proctoring_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringdata',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
