# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_proctoring_system', '0004_proctoringconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringconfiguration',
            name='proctored_exam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctoringconfiguration_exam', to='edx_proctoring.ProctoredExam'),
        ),
    ]
