# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_proctoring_system', '0006_proctoringconfiguration_enable_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringconfiguration',
            name='pop_up_window',
            field=models.BooleanField(default=True),
        ),
    ]
