# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_proctoring_system', '0007_proctoringconfiguration_pop_up_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringconfiguration',
            name='blur_restriction',
            field=models.BooleanField(default=True),
        ),
    ]
