# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20200423_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseidentifier',
            name='CourseKey',
            field=models.TextField(blank=True),
        ),
    ]
